### ISSUE TITLE
Attempting to deploy a sample vision model from Azure Percept Studio fails with generic error

### ISSUE THREAD

**Issue by jdiekhoff** [microsoft/Project-Santa-Cruz-Preview#168] opened 2021-03-18 16:14 UTC
I'm trying to deploy the people detection sample vision model in Azure Percept Studio to my device. It fails with a generic error, I'm not sure what next steps to take.

![2021-03-18_12-12-29](https://user-images.githubusercontent.com/1173121/111659302-7f6b5a80-87e3-11eb-84ae-5bfc9524ee8d.png)

**Comment by v-iskha** [comment] 2021-03-18 17:33
@jdiekhoff - Hi Joseph, please use this [troubleshooting guide](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/general/troubleshooting/vision_solution_troubleshooting.md) and let us know if that helps.

**Comment by jdiekhoff** [comment] 2021-03-18 18:23
@v-iskha thank you, I've gone through the troubleshooting guide and I'm unsure of what steps to take to resolve this. The azureeyemodule is reporting as running, and I'm able to view the video stream. I don't know why I'm getting a generic deployment error when trying to deploy a sample model. What logs should I be checking for deployment errors?

**Comment by v-iskha** [comment] 2021-03-18 19:21
@jdiekhoff - That was the first step to check which seems good now. Sometimes the azureeyemodule does not load the default container properly. Could you share the screenshot for "IoT Edge Runtime Response" (Attaching sample screenshot)
![image](https://user-images.githubusercontent.com/65275223/111684790-26d0a780-884d-11eb-98fb-35a6b2bfa5b8.png)

**Comment by jdiekhoff** [comment] 2021-03-18 20:07
@v-iskha Thank you, I've included a screenshot of the IoT Edge Runtime Response and the azureeyemodule. 
![2021-03-18_16-03-41](https://user-images.githubusercontent.com/1173121/111690807-08928980-8804-11eb-8d12-dcb7210eaba9.png)
![2021-03-18_16-05-58](https://user-images.githubusercontent.com/1173121/111690822-0cbea700-8804-11eb-9a32-738c3d4f5520.png)

**Comment by v-iskha** [comment] 2021-03-18 22:49
@jdiekhoff - Hi Joseph, the IoT Edge Response looks good to me. Please also share the device logs for investigation. 
You can share the logs generated from the following commands?
sudo docker logs azureeyemodule > azureeyemodule.log
sudo docker logs edgeAgent >edgeAgent.log

**Comment by v-iskha** [comment] 2021-03-19 01:56
@jdiekhoff - Follow these steps

1.	Goto Azure Portal
2.	Select Iot Edge and click on your device under the Device ID tab.
3.	Goto Modules tab
4.	Click on “Azureeyemodule”
5.	On top, click on “Module Identity Twin”
6.	On Line # 21, you will find “ModelZipUrl”:””,
7.	In the double quotes enter https://aedsamples.blob.core.windows.net/vision/aeddevkitnew/product-detection.zip
8.	It will now look as “ModelZipUrl” : “https://aedsamples.blob.core.windows.net/vision/aeddevkitnew/product-detection.zip”
9.	Save it
10.	If the runtime status of azureeyemodule is not listed as running, click Set modules -> azureeyemodule. On the Module Settings page, set Desired Status to running and click Update.

Once above steps are completed, check if vision module shows as deployed. Try to deploy a sample model.

For screenshot/guide refer this [link](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/prototyping/containers/eye_module_overview.md#how-to-locate-and-edit-your-module-identity-twin-settings).

Let us know the outcome.

**Comment by lxyea** [comment] 2021-03-22 02:00
@v-iskha I've just followed all your steps above, and added the URL address, still the same error message.
![image](https://user-images.githubusercontent.com/17607036/111931118-a17c1a00-8b0e-11eb-8562-3377a92c0891.png)

**Comment by v-iskha** [comment] 2021-03-22 05:24
@lxyea - Forgot to mention that sometimes after the "Azuremodule" update we need to restart the device and the "Azure portal". Let us know the outcome.

**Comment by v-iskha** [comment] 2021-03-25 23:56
@lxyea - Hi Larry, could you please share the device logs for investigation.
You can share the logs generated from the following commands?
sudo docker logs azureeyemodule > azureeyemodule.log
sudo docker logs edgeAgent >edgeAgent.log

**Comment by lxyea** [comment] 2021-03-31 00:21
> @lxyea - Hi Larry, could you please share the device logs for investigation.
> You can share the logs generated from the following commands?
> sudo docker logs azureeyemodule > azureeyemodule.log
> sudo docker logs edgeAgent >edgeAgent.log

Hi iskha, apologies for the late reply. I've just tried above commands in the az cli, however, it seems not working for me. Could you please give me more detailed instruction? Thanks a lot.

**Comment by lxyea** [comment] 2021-03-31 00:22
> @lxyea - Forgot to mention that sometimes after the "Azuremodule" update we need to restart the device and the "Azure portal". Let us know the outcome.

I've restarted, it remains the same error.

**Comment by jdiekhoff** [comment] 2021-04-07 17:10
@v-iskha This device has now become completely unresponsive. It's no longer able to connect to IoT Hub, nor does the SoftAP work to start the OOBE to attempt to fix.

**Comment by v-iskha** [comment] 2021-04-07 19:03
@jdiekhoff - Please delete the device from the IoT hub and then re-register through the OOBE process. The device should be able to connect in IoT Hub.

**Comment by mklasby** [comment] 2021-04-08 22:54
We are having the same issue with 4 different devices, please advise.

**Comment by v-iskha** [comment] 2021-04-08 23:10
@tsampige - Need your expertise here. Multiple devices has become completely unresponsive. It's no longer able to connect to IoT Hub, nor does the SoftAP work to start the OOBE to attempt to fix. Restarting does not help. After booting it is stuck in a state of left light solid green and right light blinking green for hours.

**Comment by edgeyoda** [comment] 2021-04-08 23:24
I've also had the same issue, can't deploy a custom vision model, tried various things. In my case it says that the model update has been successful, but in practice it does not appear to have actually updated on the device itself. I'm wondering if there is a dependency on the subscription tier. Been using the free one and run out of data quick. I think 8k messages per day is not nearly enough to experiment with deploying custom model since telemetry is sent even without anything in the camera frame. The file size is probably in megabytes?

**Comment by mklasby** [comment] 2021-04-09 03:15
@edgeyoda we are having this issue on a paid tier as well with at 400000 daily message quota

**Comment by tsampige** [comment] 2021-04-12 21:34
can you try to upgrade the azureeyemodule via the following steps and let me know if it resolves the sample deployment issue? The upgrade module also addresses the log retention issue. 
Go to IoT Hub -> IoT Edge -> Select Device -> click on Set Modules -> select azureyemodule, then change image uri to mcr.microsoft.com/azureedgedevices/azureeyemodule:2103-2 and click update -> click on Review + create -> click on create. The module download will get initiated. To verify if the download is completed, click on Azureeyemodule and check if the reported value is same as desired value.

**Comment by rjohnsonrxr** [comment] 2021-04-13 20:11
Hi, I am facing the same issue, not able to deploy models. I have tried updating the azureeyemodule version. Reported module value is still showing as the preload version after several hours. I am seeing these errors in the logs : 

Azure Eye Log : 

Error: Time:Tue Apr 13 18:28:23 2021 File:/tmp/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_http_edge.c Func:on_edge_hsm_http_recv Line:365 executing HTTP request fails, status=404, response_buffer={"message":"Module not found\n\tcaused by: Signing error occurred.\n\tcaused by: An error occurred in the key store.\n\tcaused by: HSM failure\n\tcaused by: HSM API failure occurred: 478"}
Error: Time:Tue Apr 13 18:28:23 2021 File:/tmp/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_http_edge.c Func:send_http_workload_request Line:484 send_request_to_edge_workload failed
Error: Time:Tue Apr 13 18:28:23 2021 File:/tmp/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_http_edge.c Func:hsm_client_http_edge_sign_data Line:578 send_http_workload_request failed
Error: Time:Tue Apr 13 18:28:23 2021 File:/tmp/azure-iot-sdk-c/provisioning_client/src/iothub_auth_client.c Func:sign_sas_data Line:57 Failed signing data
Error: Time:Tue Apr 13 18:28:23 2021 File:/tmp/azure-iot-sdk-c/provisioning_client/src/iothub_auth_client.c Func:iothub_device_auth_generate_credentials Line:427 Failure generate hash from tpm.
Error: Time:Tue Apr 13 18:28:23 2021 File:/tmp/azure-iot-sdk-c/iothub_client/src/iothub_client_authorization.c Func:IoTHubClient_Auth_Get_SasToken Line:421 failure getting credentials from device auth module
Error: Time:Tue Apr 13 18:28:23 2021 File:/tmp/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2188 failure getting sas token from IoTHubClient_Auth_Get_SasToken.
2021-04-13 18:28:24 nn: seqno=82582, ts=1618338504507555177, []
2021-04-13 18:28:24 nn: seqno=82587, ts=1618338504715871581, []
2021-04-13 18:28:24 nn: seqno=82589, ts=1618338504799203374, []
2021-04-13 18:28:24 nn: seqno=82594, ts=1618338505007516153, []
2021-04-13 18:28:24 nn: seqno=82598, ts=1618338505174168588, []
2021-04-13 18:28:24 nn: seqno=82601, ts=1618338505299174848, []



Edge Agent Log : 

<4> 2021-04-13 19:45:13.127 +00:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Error calling SignAsync: Module not found
	caused by: Signing error occurred.
	caused by: An error occurred in the key store.
	caused by: HSM failure
	caused by: HSM API failure occurred: 478, StatusCode: 404) (Error calling SignAsync: Module not found
	caused by: Signing error occurred.
	caused by: An error occurred in the key store.
	caused by: HSM failure
	caused by: HSM API failure occurred: 478, StatusCode: 404)
 ---> Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmComunicationException: Error calling SignAsync: Module not found
	caused by: Signing error occurred.
	caused by: An error occurred in the key store.
	caused by: HSM failure
	caused by: HSM API failure occurred: 478, StatusCode: 404
   at Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmSignatureProvider.SignAsync(String moduleId, String generationId, String data)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.ModuleAuthenticationWithHsm.SafeCreateNewToken(String iotHub, Int32 suggestedTimeToLive)
   at Microsoft.Azure.Devices.Client.AuthenticationWithTokenRefresh.GetTokenAsync(String iotHub)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTCbsTokenProvider.GetTokenAsync(Uri namespaceAddress, String appliesTo, String[] requiredClaims)
   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c__DisplayClass4_0.<SendTokenAsync>b__1(IAsyncResult a)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTCbsLink.SendTokenAsync(ICbsTokenProvider tokenProvider, Uri namespaceAddress, String audience, String resource, String[] requiredClaims, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpAuthenticationRefresher.InitLoopAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTConnection.CreateRefresherAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.CreateRefresherAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.CreateAndOpenSdkModuleClient(UpstreamProtocol upstreamProtocol, ConnectionStatusChangesHandler statusChangedHandler) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs:line 205
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmComunicationException: Error calling SignAsync: Module not found
	caused by: Signing error occurred.
	caused by: An error occurred in the key store.
	caused by: HSM failure
	caused by: HSM API failure occurred: 478, StatusCode: 404
   at Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmSignatureProvider.SignAsync(String moduleId, String generationId, String data)
   at Microsoft.Azure.Devices.Client.HsmAuthentication.ModuleAuthenticationWithHsm.SafeCreateNewToken(String iotHub, Int32 suggestedTimeToLive)
   at Microsoft.Azure.Devices.Client.AuthenticationWithTokenRefresh.GetTokenAsync(String iotHub)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTCbsTokenProvider.GetTokenAsync(Uri namespaceAddress, String appliesTo, String[] requiredClaims)
   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c__DisplayClass4_0.<SendTokenAsync>b__1(IAsyncResult a)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTCbsLink.SendTokenAsync(ICbsTokenProvider tokenProvider, Uri namespaceAddress, String audience, String resource, String[] requiredClaims, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpAuthenticationRefresher.InitLoopAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTConnection.CreateRefresherAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.CreateRefresherAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.CreateAndOpenSdkModuleClient(UpstreamProtocol upstreamProtocol, ConnectionStatusChangesHandler statusChangedHandler) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs:line 205
   at Microsoft.Azure.Devices.Edge.Util.Fallback.ExecuteAsync[T](Func`1[] options)<---
<4> 2021-04-13 19:45:19.170 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (/tmp/edgeAgent/backup.json) instead
<4> 2021-04-13 19:45:29.280 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (/tmp/edgeAgent/backup.json) instead
<4> 2021-04-13 19:45:39.411 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (/tmp/edgeAgent/backup.json) instead
<4> 2021-04-13 19:45:48.243 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (/tmp/edgeAgent/backup.json) instead
<4> 2021-04-13 19:45:58.414 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (/tmp/edgeAgent/backup.json) instead

**Comment by tsampige** [comment] 2021-04-13 23:03
can you email aedppsup for a workaround to address this issue?

**Comment by rjohnsonrxr** [comment] 2021-04-14 13:26
Sure, what's the email address?

**Comment by v-prsasa** [comment] 2021-04-14 13:28
@rjohnsonrxr Kindly mail on this id- aedppsup@microsoft.com

**Comment by v-iskha** [comment] 2021-04-15 23:42
@rjohnsonrxr - Since the issue seems fixed after the workaround, we are closing this issue.

**Closed by v-iskha** 2021-04-15 23:42 UTC
Labels: bug

**Comment by mklasby** [comment] 2021-04-17 02:51
@v-iskha confirmed fixed on our end, thanks!
